In [38]:
import numpy as np
import cmath

In [39]:
arr1=np.arange(40).reshape(8,5)
arr1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [40]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
arr1[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [41]:
 #Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34}
arr1[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [42]:
# Setup for next question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2


array([[1421, 3399, 5709, 5825, 4446],
       [1240, 6294, 8949, 2708, 3635]])

In [43]:
#Normalization rescales the values into a range of [0,1].
#This might be useful in some cases where all parameters need to have the same positive scale. 
#You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). 
#The formula for normalization is given below
# Xchanged=(X−Xmin)/(Xmax−Xmin)
# Q3. Write a code to normalize arr2.
(arr2-arr2.min())/(arr2.max()-arr2.min())

array([[0.02347905, 0.28006226, 0.57971202, 0.59475937, 0.41587755],
       [0.        , 0.65559735, 1.        , 0.19042677, 0.31067583]])

In [44]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai
arr4=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
np.isnan(arr4)



array([[False, False,  True],
       [False, False, False],
       [ True,  True, False]])

In [45]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

a=np.arange(6)
a
n=3
a.sort()
a[len(a)-n]




3

In [46]:
# Setup for next questions

arr3=np.arange(20).reshape(4,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
# Q6 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing
x=arr3[:,0].copy()
arr3[:,0]=arr3[:,-2]
x

array([ 0,  5, 10, 15])

In [48]:
arr3[:,[-2,1,2,0,-1]]

array([[ 3,  1,  2,  3,  4],
       [ 8,  6,  7,  8,  9],
       [13, 11, 12, 13, 14],
       [18, 16, 17, 18, 19]])

In [49]:
arr3[:,-2]=x
arr3

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [50]:
# Q7 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
arr3[3::-1]

array([[18, 16, 17, 15, 19],
       [13, 11, 12, 10, 14],
       [ 8,  6,  7,  5,  9],
       [ 3,  1,  2,  0,  4]])

In [51]:
# Set up for next question

arr4=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr4

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [52]:
# Q8 Write a code to replace all the nan(missing values) of arr4 with the mean of arr4
arr4[np.isnan(arr4)]=np.nanmean(arr4)
arr4

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [55]:
# Set up for next question

arr5=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr5

array([[58, 31, 22, 99],
       [25, 72, 88,  3],
       [16, 37, 55, 89],
       [94, 98, 40, 77],
       [67, 69, 76, 98]])

In [56]:
# Q9 Write a code which can fetch all items from arr5 which are either greater than 25 or a multiple of 3
arr5[(arr5>25) & (arr5%3==0) ]

array([99, 72, 69])

In [57]:
# Q10 Write a code to find the 10th, 25th, 50th(median) percentile of arr5
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [58]:
np.percentile(arr5,10)

21.400000000000002

In [59]:
np.percentile(arr5,25)

35.5

In [60]:
np.percentile(arr5,50)

68.0